updated cd file

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -18,16 +18,15 @@ jobs:
                   username: ${{ secrets.EC2_USER }}
                   key: ${{ secrets.EC2_SSH_KEY }}
                   
-                  script: |
-                           
-                    if [ ! -d ~/skill-meter-project ]; then
-                      git clone ${{ github.server_url }}/${{ github.repository }}.git ~ /skill-meter-project
-                      fi
-                      cd ~/skill-meter-project
-                      git pull origin main
-                    if [ ! -f .env ]; then
-                        echo "ERROR: ~/skill-meter-project/.env is missing. create it with DOCkERHUB_USERNAME and DB credentials."
-                     exit 1
+                  script: |     
+                     if [ ! -d ~/skill-meter-project ]; then
+                     git clone ${{ github.server_url }}/${{ github.repository }}.git ~ /skill-meter-project
+                     fi
+                     cd ~/skill-meter-project
+                     git pull origin main
+                     if [ ! -f .env ]; then
+                       echo "ERROR: ~/skill-meter-project/.env is missing. create it with DOCkERHUB_USERNAME and DB credentials."
+                       exit 1
                      fi
 
                      docker compose pull
